server {
    listen 80;
    server_name _;

    # ── Frontend (SPA) ──────────────────────────────────
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── Catalogue API ───────────────────────────────────
    location /api/catalog/ {
        proxy_pass http://catalogue-service:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── Orders API (Django — trailing slash requis) ─────
    location /api/orders/ {
        proxy_pass http://order-service:8000/api/orders/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── Payment API ─────────────────────────────────────
    location /api/payments {
        proxy_pass http://payment-service:8082/api/payments;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
