replicaCount: 2
namespace: prod
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: false

configmap:
  CATALOG: "http://prod.98.66.248.206.nip.io/api/products"
  # URL prod → le front appelle les APIs via le bon hostname
  # → NGINX route vers les services du namespace prod
  ORDERS: "http://prod.98.66.248.206.nip.io/api/orders"
  PAYMENT: "http://prod.98.66.248.206.nip.io/api/payments"
  AUTH_ENABLED: "false"

hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
