replicaCount: 2
namespace: qualif

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: true
  name: ecommerce-ingress-qualif
  # Nom différent de dev → pas de conflit de ressource dans le namespace qualif
  host: qualif.98.66.248.206.nip.io
  # Sous-domaine qualif → NGINX accepte car (host, path) est unique
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  routes:
    - path: /api/products
      pathType: Prefix
      service:
        name: catalogue
        port: 4000
    - path: /api/orders
      pathType: Prefix
      service:
        name: order
        port: 8000
    - path: /api/payments
      pathType: Prefix
      service:
        name: payment
        port: 8082
    - path: /
      pathType: Prefix
      service:
        name: front
        port: 80

configmap:
  CATALOG: "http://qualif.98.66.248.206.nip.io/api/products"
  # URL qualif → le front appelle les APIs via le bon hostname
  # → NGINX route vers les services du namespace qualif
  ORDERS: "http://qualif.98.66.248.206.nip.io/api/orders"
  PAYMENT: "http://qualif.98.66.248.206.nip.io/api/payments"
  AUTH_ENABLED: "false"

hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
