image:
  repository: docker.io/jubatouam/front
  tag: "7.0"
  pullPolicy: Always

replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: 0

affinity:
  nodepool: apps

service:
  type: ClusterIP
  port: 80

probes:
  path: /
  startup:
    periodSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 15
    failureThreshold: 3
  readiness:
    periodSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

configmap:
  CATALOG: ""
  ORDERS: ""
  PAYMENT: ""
  AUTH_ENABLED: "false"

secret:
  enabled: false
  data: {}

initContainer:
  env: []

rollout:
  enabled: false
  strategy:
    blueGreen:
      activeService: front
      previewService: front-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 600

ingress:
  enabled: true
  name: ecommerce-ingress
  className: kong
  annotations: {}
  routes:
    - path: /
      pathType: Prefix
      service:
        name: front
        port: 80
